"""
MCP Reporter Agent - Generates security scan reports
Port: 8003
"""
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List
from datetime import datetime
import os
from supabase_client import supabase

app = FastAPI(title="Reporter Agent", version="1.0.0")

class Vulnerability(BaseModel):
    id: str = None
    vulnerability_type: str
    severity: str
    file_path: str
    line_number: int = None
    description: str
    tool: str = None

class ReportRequest(BaseModel):
    scan_id: str
    vulnerabilities: List[Vulnerability]

class ReporterAgent:
    async def generate_report(self, scan_id: str, vulnerabilities: list) -> str:
        """Generate markdown security report"""
        
        # Fetch scan details
        scan_data = supabase.table("scans").select("*").eq("id", scan_id).execute()
        if not scan_data.data:
            raise Exception("Scan not found")
        
        scan = scan_data.data[0]
        
        # Generate report
        report_md = f"""# Security Scan Report
        
## Scan Information
- **Scan ID**: {scan_id}
- **Repository**: {scan.get('repository_id', 'N/A')}
- **Status**: {scan.get('status', 'N/A')}
- **Started**: {scan.get('scan_started_at', 'N/A')}
- **Completed**: {scan.get('scan_completed_at', 'N/A')}
- **Generated**: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}

## Summary
- **Total Vulnerabilities**: {len(vulnerabilities)}
- **Critical**: {sum(1 for v in vulnerabilities if v.get('severity') == 'critical')}
- **High**: {sum(1 for v in vulnerabilities if v.get('severity') == 'high')}
- **Medium**: {sum(1 for v in vulnerabilities if v.get('severity') == 'medium')}
- **Low**: {sum(1 for v in vulnerabilities if v.get('severity') == 'low')}

## Vulnerabilities

"""
        
        # Group by severity
        for severity in ['critical', 'high', 'medium', 'low']:
            severity_vulns = [v for v in vulnerabilities if v.get('severity') == severity]
            if severity_vulns:
                report_md += f"\n### {severity.upper()} Severity\n\n"
                for i, vuln in enumerate(severity_vulns, 1):
                    report_md += f"#### {i}. {vuln.get('vulnerability_type', 'Unknown')}\n\n"
                    report_md += f"- **File**: `{vuln.get('file_path', 'N/A')}`\n"
                    if vuln.get('line_number'):
                        report_md += f"- **Line**: {vuln['line_number']}\n"
                    report_md += f"- **Tool**: {vuln.get('tool', 'N/A')}\n"
                    report_md += f"- **Description**: {vuln.get('description', 'N/A')}\n\n"
                    
                    # Fetch AI fix from ai_fixes table
                    if vuln.get('id'):
                        try:
                            fix_data = supabase.table("ai_fixes").select(
                                "suggested_fix, confidence_score, ai_model"
                            ).eq("vulnerability_id", vuln['id']).execute()
                            
                            if fix_data.data:
                                fix = fix_data.data[0]
                                confidence = fix.get('confidence_score', 0.0)
                                report_md += f"**AI-Generated Fix** (Confidence: {confidence*100:.0f}%, Model: {fix.get('ai_model', 'N/A')}):\n"
                                report_md += f"```\n{fix.get('suggested_fix', 'No fix available')}\n```\n\n"
                            else:
                                report_md += "**AI Fix**: Not yet generated\n\n"
                        except Exception as e:
                            print(f"Error fetching fix for vuln {vuln['id']}: {e}")
                            report_md += "**AI Fix**: Error fetching fix\n\n"
                    else:
                        report_md += "**AI Fix**: Vulnerability ID missing\n\n"
        
        report_md += "\n---\n*Report generated by SecureShift Autonomous Security Agent*\n"
        
        # Store report in Supabase (as text for now, can upload to S3 later)
        report_url = f"/reports/{scan_id}"
        
        # Update scan with report
        supabase.table("scans").update({
            "report_url": report_url
        }).eq("id", scan_id).execute()
        
        # Store report content in scan_logs
        supabase.table("scan_logs").insert({
            "scan_id": scan_id,
            "log_level": "info",
            "message": "Report generated",
            "details": {"report": report_md}
        }).execute()
        
        return report_url

reporter = ReporterAgent()

@app.post("/generate-report")
async def generate_report_endpoint(request: ReportRequest):
    """Generate security scan report"""
    try:
        report_url = await reporter.generate_report(
            request.scan_id,
            [v.dict() for v in request.vulnerabilities]
        )
        return {"status": "success", "report_url": report_url}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/health")
async def health():
    return {"status": "healthy", "service": "reporter"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8003)